### ISSUE TITLE
Hitting Undo in the design tool deselects the element

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1283] opened 2021-05-19 14:49 UTC
**STR**
1. Insert a View
2. change its layout to 'flow'
3. CMD+Z

Expected: stays selected
Observed: gets deselected

**Comment by seanparsons** [comment] 2021-05-27 10:56
I've been unable to reproduce this, potentially this has been fixed by #1308 and/or some other fixes.

**Closed by seanparsons** 2021-05-27 10:56 UTC
Labels: Bug
