### ISSUE TITLE
Bug: resizing the code editor scrolls the editor

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1483] opened 2021-07-12 11:38 UTC
**STR**
1. New project
2. Resize the code editor left-right a few times in one drag
3. (possibly) click into the code editor or onto the navigator

Observed: entire editor scrolls, cutting 20px or so of the top of the editor in the process. Can't scroll back

Expected: No scrolling

(NEW) Video:

https://user-images.githubusercontent.com/2945037/125282107-ecfd4280-e30e-11eb-8f33-04e5e9da1624.mp4

![image](https://user-images.githubusercontent.com/2945037/125281488-2ed9b900-e30e-11eb-8960-07338e153d2c.png)

**Comment by Rheeseyb** [comment] 2021-07-12 12:51
This is a duplicate of #1469, but I'll close that one as this has a video which will help with the repro

**Comment by Rheeseyb** [comment] 2021-09-24 13:41
This was fixed by #1630

**Closed by Rheeseyb** 2021-09-24 13:41 UTC
