### ISSUE TITLE
Canvas performance degrades when an image has `base64` data in `src`

### ISSUE THREAD

**Issue by bkrmendy** [concrete-utopia/utopia#2666] opened 2022-10-14 09:23 UTC
## Describe the bug
Canvas interaction performance degrades when manipulating images that have `base64` data in `src`

## To Reproduce
Drag and drop an image into the canvas while logged out. This way, the image is not uploaded to the assets folder, but instead the image data is inserted as `base64` into the `src` field of the newly created `img`. 

Result: dragging around the `img` becomes noticeably slower

## Expected behaviour
Performance stays the same

## Screenshots
Profiling canvas interactions on an image with base64 data
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/16385508/195811791-a2027aa5-20e7-4160-8e76-a245b1db6203.png">

**Comment by ruggi** [comment] 2022-10-18 11:33
A bit more digging 🕵️‍♂️: it looks like the problem is in the parsing of large strings:

```ts
const Foo = () => {
  return <img src="data:image/png;base64,..." />
}
```

is crazy slow, but
```ts
const data = "data:image/png;base64,..."

const Foo = () => {
  return <img src={data} />
}
```

is perfectly fine.

**Comment by maltenuhn** [comment] 2022-10-18 11:35
Is this our parser/printer parsing specifically? Or another system?

**Comment by ruggi** [comment] 2022-10-18 11:36
I _think_ so, but actually it could still be the rendering, I'm still looking into it

**Comment by ruggi** [comment] 2022-10-18 11:36
The problem _only_ appears when dragging _the image_ and not e.g. the container of the image itself

**Comment by balazsbajorics** [comment] 2022-10-18 11:57
the parser-printer should be dormant during canvas interactions. if the performance is only bad if you interact with the image, then the place I'd start digging is here: https://github.com/concrete-utopia/utopia/blob/39d81d0f8f3171b477af7f9e74525a5719c43a28/editor/src/components/canvas/ui-jsx-canvas-renderer/ui-jsx-canvas-component-renderer.tsx#L81 
but it sounds like the problem can be anywhere from the ComponentRendererComponent, React updating the DOM, or the DOM being updated and chrome re-evaluates that inline string.

Did anyone manage to reproduce the slowness in codesandbox? The fact that the slowness seem to come from that Layout block suggests to me that we are triggering some sort of Chrome sad path. Which means we _should be_ able to reproduce the problem outside of utopia.

**Comment by ruggi** [comment] 2022-10-18 12:31
> Did anyone manage to reproduce the slowness in codesandbox? The fact that the slowness seem to come from that Layout block suggests to me that we are triggering some sort of Chrome sad path. Which means we should be able to reproduce the problem outside of utopia.

I hacked together the dragging in Codesandbox and it seems to be working fine (e.g. https://codesandbox.io/s/loving-elgamal-uelduq?file=/src/App.js)

**Comment by ruggi** [comment] 2022-10-18 13:46
As per the related discussion, closing this for now as a `wontfix` since the scope for the issue is only relevant when the `img` itself is dragged, not the container elements.

**Closed by ruggi** 2022-10-18 13:46 UTC
