### ISSUE TITLE
Inspector controls 'flicker' or disappear while typing

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1030] opened 2021-03-31 12:45 UTC
**Describe the bug**
While typing code, some inspector controls rapidly change state, including ones not related to the property being edited

**To Reproduce**
1. Open this test project https://utopia.pizza/p/a645be4c-alpine-climb/
2. Edit the `hr` and set its color prop to `yellow` or `orange`

Observed: the inspector 'flickers', some row / controls seem to disappear and then quickly re-appear - see attached video

**Expected behaviour**
No flickering, inspector rows stay the same.

**Video**
https://user-images.githubusercontent.com/2945037/113146160-3ece0100-9227-11eb-9e86-45770f58cb86.mp4

**Comment by Rheeseyb** [comment] 2021-04-06 11:29
This is caused by the UID of the selection changing. The only way to fix this is to attempt to retain UIDs during the parsing of the code somehow, which requires discussion.

**Comment by Rheeseyb** [comment] 2021-04-21 10:21
Closed by #1102

**Closed by Rheeseyb** 2021-04-21 10:21 UTC
Labels: Code / Parsing, Inspector, Perceived Bug
