### ISSUE TITLE
Fix being able to manipulate elements inside arbitrary JSX blocks.

### ISSUE THREAD

**Issue by seanparsons** [concrete-utopia/utopia#834] opened 2021-01-08 15:00 UTC
Appears the recent work to support comments in arbitrary blocks has broken the ability to reproduce the code after manipulating the elements.

Sample project: [this project](https://utopia.pizza/p/4a1b2e66-elegant-wallaby/) - you are able to select the blue rectangle on the canvas and drag it or update it via the Inspector, but doing so no longer updates the code. This is a very recent regression, possibly caused by a data-uid fix that was included in #820

**Comment by Rheeseyb** [comment] 2021-01-08 15:06
Closing as duplicate of #833

**Comment by Rheeseyb** [comment] 2021-01-08 15:14
Reopening because Sean preferred his ticket

**Comment by seanparsons** [comment] 2021-01-11 10:57
Code that reproduces the issue:
```javascript
/** @jsx jsx */
import * as React from 'react'
import { Scene, Storyboard, jsx, View } from 'utopia-api'
export var App = (props) => {
  return (
    <div
      style={{ width: '100%', height: '100%', backgroundColor: '#FFFFFF', position: 'relative' }}
    >
      <div
        style={{
          position: 'absolute',
          left: 74,
          top: 78,
          width: 215,
          height: 417,
          backgroundColor: '#DDE3E7AB',
        }}
      >
        {
          <div
            style={{
              backgroundColor: '#0091FFAA',
              position: 'absolute',
              width: 86,
              height: 130,
              left: 65,
              top: 79,
            }}
          />
        }
      </div>
    </div>
  )
}
export var storyboard = (
  <Storyboard>
    <Scene
      component={App}
      props={{}}
      style={{ position: 'absolute', left: 0, top: 0, width: 375, height: 812 }}
    />
  </Storyboard>
)
```

**Closed** 2021-01-12 13:29 UTC
