### ISSUE TITLE
I can't delete elements inside a focused component

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1581] opened 2021-07-23 10:54 UTC
STR
1. I focus Card component
2. select one of the inner divs
3. Hit delete key on keyboard

Expected: it deletes
Result: nothing happens (not even a toast)

**Comment by Rheeseyb** [comment] 2021-07-23 12:37
I've just tested this and it appears to be hitting the same issues as #1558 and #1530, so I'm going to close this as a duplicate of those

**Closed by Rheeseyb** 2021-07-23 12:37 UTC
