### ISSUE TITLE
Can't import OrbitControls due to it being an ES Module

### ISSUE THREAD

**Issue by alecmolloy** [concrete-utopia/utopia#426] opened 2020-08-17 18:28 UTC
project: https://utopia.app/p/ee1a59ea-wobbly-airbus/

This very may well will be a wontfix, but this is a very very commonly used three feature, and the old package https://www.npmjs.com/package/three-orbitcontrols recommends the ES Module import.

**Comment by Rheeseyb** [comment] 2020-09-25 16:06
Closing as this is basically a duplicate of #508

**Closed by Rheeseyb** 2020-09-25 16:06 UTC
Labels: Code / Parsing
