### ISSUE TITLE
Natural Scene Composition

### ISSUE THREAD

**Issue by alecmolloy** [concrete-utopia/utopia#748] opened 2020-12-02 22:40 UTC
Users should be construct scenes as such:
```
<Scene>
  <Component>
      <div>Hello world</div>
   </Component>
</Scene>
```

Instead of having to provide the component as a render prop, and props as `props.props` on the scene. Furthermore, the children should be passed properly, as this doesn't work today.

Originated from the following bug report: 
Scene take `props.component` and `props.props`, which is passed to the component, all except for `props.props.children`. They should be passed.

**Comment by alecmolloy** [comment] 2020-12-02 22:40
Is there a reason props.children isn't passed? Is it just because of some weird special case that needs to be handled, or is there a good reason?

**Comment by maltenuhn** [comment] 2020-12-03 08:01
This is a bug. The intented solution here is to remove those props from Scene entirely and put them into the code, so you can write code like this:

```
<Scene>
  <Component>
      <div>Hello world</div>
   </Component>
</Scene>
```

**Comment by alecmolloy** [comment] 2020-12-03 17:24
thanks, have updated the card to reflect that.

**Comment by maltenuhn** [comment] 2021-02-16 14:52
Duplicate of #297

**Closed by maltenuhn** 2021-02-16 14:52 UTC
Labels: Canvas, Code / Parsing
