### ISSUE TITLE
RecoilRoot kills the navigator / controls.

### ISSUE THREAD

**Issue by balazsbajorics** [concrete-utopia/utopia#579] opened 2020-10-01 09:17 UTC
https://utopia.pizza/project/6222d0f3/

The presence of RecoilRoot makes the navigator empty. My bet is that it has something to do with DOM walking.

**Comment by balazsbajorics** [comment] 2020-10-01 09:18
you can see that with a removed RecoilRoot, it starts working: https://utopia.pizza/p/d0769e2b-youthful-goldenrod/

**Comment by seanparsons** [comment] 2020-10-14 13:51
Duplicate of https://github.com/concrete-utopia/utopia/issues/560

**Closed by seanparsons** 2020-10-14 13:51 UTC
Labels: Code / Parsing
