### ISSUE TITLE
Crashing bug while typing a change to a style property

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1371] opened 2021-06-14 19:04 UTC
**Fatal crashing bug**
(editing style tag takes down the editor) https://paradise-engineering.slack.com/archives/C1VLFSW0H/p1623693267017500

STR: ~not entirely clear, but involved editing the `style` part of a component. In the Slack link ^^^ there's React devtools download, and screenshots of the console~
1) Start with the code `<div style= />` anywhere in your project
2) Updated that to `<div style="r" />`
3) Don't profit :disappointed:

Also, if you open this project it (still) seems to show the error that initially took down the editor.

https://utopia.app/p/ec77ab7c-lyrical-candle/

**Comment by Rheeseyb** [comment] 2021-06-14 19:12
I just tested this out and updated with steps to reproduce. The issue seems to be that a string is being passed in rather than an object (for the style prop), but I haven't looked into why that completely breaks the editor.

**Comment by maltenuhn** [comment] 2021-06-14 19:18
Yeah, this happened mid-edit (my intention was to remove the style object, and replace it with className, possibly repurposing part of the string _from_ the style object - or maybe my hand slipped and I typed in the wrong place. The issue for me isn't the error, but that producing that error state took down the editor (since it's the kind of error you could also get while eg _completing_ a style object, or going from "oops, only one set of curly braces, needs to").

**Comment by Rheeseyb** [comment] 2021-06-18 16:02
Closing as this appears to have been fixed since filing (I suspect by #1359)

**Closed by Rheeseyb** 2021-06-18 16:02 UTC
Labels: Bug, Severe

**Comment by maltenuhn** [comment] 2021-06-18 16:06
Huh! I really didn't expect #1359 to be the root cause here...
